export const users = [
  {
    name: 'John Doe',
    email: 'john.doe@example.com',
    role: 'Administrator',
    status: 'Active',
    phoneNumber: '+1 (555) 123-4567',
  },
  {
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    role: 'Editor',
    status: 'Inactive',
    phoneNumber: '+1 (555) 234-5678',
  },
  {
    name: 'Emily Johnson',
    email: 'emily.johnson@example.com',
    role: 'Subscriber',
    status: 'Active',
    phoneNumber: '+1 (555) 345-6789',
  },
  {
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    role: 'Administrator',
    status: 'Active',
    phoneNumber: '+1 (555) 456-7890',
  },
  {
    name: 'Sarah Davis',
    email: 'sarah.davis@example.com',
    role: 'Editor',
    status: 'Inactive',
    phoneNumber: '+1 (555) 567-8901',
  },
  {
    name: 'David Wilson',
    email: 'david.wilson@example.com',
    role: 'Subscriber',
    status: 'Active',
    phoneNumber: '+1 (555) 678-9012',
  },
  {
    name: 'Olivia Martinez',
    email: 'olivia.martinez@example.com',
    role: 'Editor',
    status: 'Active',
    phoneNumber: '+1 (555) 789-0123',
  },
  {
    name: 'Daniel Lee',
    email: 'daniel.lee@example.com',
    role: 'Administrator',
    status: 'Inactive',
    phoneNumber: '+1 (555) 890-1234',
  },
  {
    name: 'Sophia Walker',
    email: 'sophia.walker@example.com',
    role: 'Subscriber',
    status: 'Active',
    phoneNumber: '+1 (555) 901-2345',
  },
  {
    name: 'James Harris',
    email: 'james.harris@example.com',
    role: 'Editor',
    status: 'Inactive',
    phoneNumber: '+1 (555) 012-3456',
  },
];
